trigger:
  batch: true
  branches:
    include: 
    - 'master'
  paths:
    include: 
    - webapp/
    
pr: none

variables: 
  agentPoolName: 'Pipeline-webapp'
pool:
  name: $(agentPoolName)
  #vmImage: $(Pipeline-webapp)
#pool: self-hosted # If you are running self-hosted Azure DevOps Agents

stages:
# Refering the pipeline template, input parameter that are not specified will be added with defaults
- template: ./pipeline_templates/main_template.yaml
  parameters:
    #serviceConnectionName: azuredevops_service_connection
    awsRegion: us-west-1
    awsEKSClusterName: 1STI
    awsEKSRegion: us-west-1
    awsECRRegion: us-west-1
    #projectName: webapp
