apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
data:
  index.html: |
    <head>
    <title>My App 1STI</title>
    </head>
    <body>
    <div>    
      <div>
        <h1>
        Deploy de Kubernetes no Amazon EKS utilizando o Azure DevOps</h1>
        <h2>
            The Versão do App: {{.Values.appversion}}</h2>
        <h3>Links</h3>
        <ul>
            <li>
                <a href="https://apg-library.amazonaws.com/" target="_blank" rel="noopener">APG Library</a>
            </li>
        </ul>
      </div>
    </div>
    </body>
